# Controls when the action will run. Triggers the workflow on push request for the master branch
name: deploy

on:
  repository_dispatch:
    types: [start_deploy]
    branches: [release]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to LeanEngine
        uses: enflo/curl-action@v1.2
        with:
          curl: -X POST https://leancloud.cn/1.1/engine/groups/web/production/version?gitTag=release&token=${{ secrets.LEANCLOUD_DEPLOY_TOKEN }}
          # curl: -X POST https://console.leancloud.app/1.1/engine/groups/web/production/version?gitTag=release&token=${{ secrets.LEANCLOUD_DEPLOY_TOKEN }}
